# ==========================================
# Database Connection Settings
# ==========================================
spring.datasource.url=jdbc:mysql://localhost:3306/ai_cosmetic_marketplace?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Deepana#609
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==========================================
# JPA / Hibernate Settings
# ==========================================
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update


# Server Port (Default is 8080, we can keep it)
server.port=8080